### ISSUE TITLE
change format for user locations

### ISSUE THREAD

**Issue by zpine1** [zpine1/deejays#10]
Change user location fields to this format: City ______, State/Province/Region_______, Country_______, with the middle field optional and the others required. I can manually fix old ones using edit info once this is changed.

**Comment by dancinglightning** [comment]
state added, 68eef7f

**Comment by zpine1** [comment]
Can we call that field "State/Province" instead of "State" ? I think leaving out "region" is a good idea. There is a lot online about this, for example: http://ux.stackexchange.com/questions/64665/address-form-field-for-region . We have lots of people from Canada in the group, and they use Province not State.
