### ISSUE TITLE
Questions about making a system for keeping local backups on my computer for data and the app

### ISSUE THREAD

**Issue by zpine1** [zpine1/deejays#21]
**Backing up Data:**

**PG backups:**

I have learned to make a PG backup manually here: https://postgres.heroku.com/databases/deejays-database#snapshots , using the gear icon in the upper right. After making it, I can download it using the download button. I have done so on 2/11/16 .

With a "hobby" account, Heroku will retain 2 backups, and drop the older when a new one comes in. One can issue a command to request daily backups, as shown here: https://devcenter.heroku.com/articles/heroku-postgres-backups#scheduling-backups. I like that idea.
To do that, I think I need to use the heroku command line. Is it correct that in order to this, I need to get the heroku toolbelt on my mac, like this: https://toolbelt.heroku.com/ ? Should I do that?

Heroku has procedures for manually restoring a PG backup. Are these PG database backups in a format that is standard so that they could be uploaded and used by other hosts in the future if needed?

 **Dataclips**
To get the data in CSV and XLS formats, I could use dataclips, as described here: https://devcenter.heroku.com/articles/dataclips . I just have to go to https://dataclips.heroku.com/clips , and then enter an SQL query to generate the clip I want , then I can download it.
I am guessing we have a table for songs, a table for users, and one for genres. 
I think I just need to say in the SQL window  **SELECT * FROM _table_name_;** for each table we have. Can you tell my what those tables are named?

**Backing up App**
I think I can go to https://github.com/zpine1/deejays/tree/master and click on "Download ZIP" near the top right. Is that all I need?

**Comment by dancinglightning** [comment]
these are actually 3 issues, cleaner to keep them apart.
1- as far as i know, yes get the toolbelt to make (binary) backups. Those are in a format that is used for a restore. 
2  - no idea. I just know you can download the backups, and i would think there is a utility to transform it into cvs. Why you would need cvs i don't know, as you have the app.
3- yes.

**Comment by zpine1** [comment]
OK, I'll just do a weekly backup of the PG database via heroku, and the app via github. Thanks!
