### ISSUE TITLE
What is "count" in user list doing, and why is it useful?

### ISSUE THREAD

**Issue by zpine1** [zpine1/deejays#6]
What is “count” in user list counting? What I see is that it resets to 0 when you add a song, then increases each time you access the song database. Is that right? Why is this important?

**Comment by dancinglightning** [comment]
This is a field that only you see.
I just thought i put it up because it's in the db.

Currently the check for having to add a new song is 
a) more than a month after last given date
b) count > 10 

b means people who look at the db once a month can do so 10 times.
I was going to make the 10 configurable for you, and with that column you have  a way to asses what a good number is.

**Comment by zpine1** [comment]
OK I understand, and I like being able to see the count. But I'd like to make the check for having to add a new song be only "more than a month after last given date." Assessing how much users are using the db is still useful for me though.

**Comment by dancinglightning** [comment]
I made this exactly how we talked about.
I thought we's agreed that just the month would be very restrictive for infrequent users.
Technically not a problem off course, i'd just encourage you to think about that once more from the point of view of an infrequent user. Basically i think you'd loose users that way.

**Comment by zpine1** [comment]
Sorry Torsten, I think I must not have been clear in communicating during in our first meeting. I've thought about it more now, and I still like just having the one month time factor for now, rather than also using count as a criterion. It simplifies the "give to get" rules as they are so nicely put in the current home and add a song pages. I do like being able to see the count though, as it may guide us in the future. I myself use the database once or twice a month usually, leaving the database open for a long time and looking at all the recently added songs, listening to samples, and getting the ones I like.

**Comment by dancinglightning** [comment]
Off course it's your user-base and i'll do it.

But just to point out the error in your thinking there: the usage you describe is with the old system.
This system is paged. Any view will get you a list of 25 songs, every refresh counts as a separate view, every search is a separate view, going to page 2 (etc) are all separate views.
So it's quite different i think, but ok.

**Comment by zpine1** [comment]
I see what you mean about pages/views. Now that we have search and sort,
people may use a lot more views, I agree. Thanks for trying it this simple
one-month way. We will be able to use your "count" to see what people are
doing.
How are the travels doing? It's been such a hot spell in the west and
southwest, is that ok for you, or a shock to your system?
-Z

**Comment by dancinglightning** [comment]
First time that we actually sit in the sun today. Nice, not too hot.
Nice to be on break, though. We're looking to arrive on the 20th at the moment, may still change a day though.
