### ISSUE TITLE
More descriptive langauge about why to use a unique password on signup

### ISSUE THREAD

**Issue by zpine1** [zpine1/deejays#9]
On signup form, it says “Password: we recommend not to use a password you use for any other site, as traffic to this site is open.” I don’t think people will understand what “traffic to this site is open” means. Is this a good alternate text? “Password: we recommend not using a password you use for any other website, because hackers could steal your email address and password from this site and use them to try to access other sites you use.” I'm open to other ideas for warning text.

**Comment by dancinglightning** [comment]
fixed by 398f5ea

definitely better
